name: "Build, test, pack, and release to NuGet"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  SOLUTION_NAME: AspNetCore.Hosting.ContentSecurityPolicies.sln
  
on:
  
  workflow_dispatch:
  push:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout source"
      id: checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      id: setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      id: restore
      run: dotnet restore ${{ env.SOLUTION_NAME }}
        
    - name: Build .NET Library
      id: build
      run: dotnet build ${{ env.SOLUTION_NAME }} -c Release --no-restore  
    
    - name: Test .NET Library
      id: test
      run: dotnet test ${{ env.SOLUTION_NAME }} --no-restore --verbosity normal
    
    - name: Pack 
      id: pack
      run: dotnet pack ${{ env.SOLUTION_NAME }} --no-build -c Release -o nupkgs
        
    - name: NuGet Push
      id: push
      working-directory: nupkgs
      run: dotnet nuget push AspNetCore.Hosting.ContentSecurityPolicies.*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate -k  ${{ env.NUGET_API_KEY }}
