name: "Build, test, pack, and release to NuGet"

on:
  
  workflow_dispatch:
  push:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
    - name: "Checkout source"
      id: checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      id: setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build .NET Library
      id: build
      uses: Elskom/build-dotnet@v1.1.1
      with:
        TEST: true
        PUSH: true
